"""initial schema

Revision ID: 0adc4fe68591
Revises: 
Create Date: 2026-08-05 08:43:31.271864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0adc4fe68591'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_tag', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tg_tag'), ['tg_tag'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)

    op.create_table('balance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('game_index', sa.Integer(), nullable=False),
    sa.Column('stats_json', sa.Text(), nullable=True),
    sa.Column('stats_source', sa.String(length=16), nullable=True),
    sa.Column('diag_json', sa.Text(), nullable=True),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('issues_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'game_index', name='uq_balance_doc_game')
    )
    with op.batch_alter_table('balance_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_reports_document_id'), ['document_id'], unique=False)

    op.create_table('diagnosis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('game_index', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('triage_json', sa.Text(), nullable=True),
    sa.Column('triage_issues_json', sa.Text(), nullable=True),
    sa.Column('kept_requests_json', sa.Text(), nullable=True),
    sa.Column('dropped_requests_json', sa.Text(), nullable=True),
    sa.Column('extra_runs_json', sa.Text(), nullable=True),
    sa.Column('runs_error', sa.Text(), nullable=True),
    sa.Column('findings_json', sa.Text(), nullable=True),
    sa.Column('issues_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'game_index', name='uq_diagnosis_doc_game')
    )
    with op.batch_alter_table('diagnosis_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_reports_document_id'), ['document_id'], unique=False)

    op.create_table('game_skeletons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('game_index', sa.Integer(), nullable=False),
    sa.Column('simulatable', sa.Boolean(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('player_counts_json', sa.Text(), nullable=True),
    sa.Column('assumptions_json', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('missing_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('issues_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'game_index', name='uq_skeleton_doc_game')
    )
    with op.batch_alter_table('game_skeletons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_skeletons_document_id'), ['document_id'], unique=False)

    op.create_table('game_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('game_index', sa.Integer(), nullable=False),
    sa.Column('spec_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('issues_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('revisions', sa.Integer(), nullable=False),
    sa.Column('revision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'game_index', name='uq_spec_doc_game')
    )
    with op.batch_alter_table('game_specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_specs_document_id'), ['document_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('game_index', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=120), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_step'), ['step'], unique=False)

    op.create_table('lens_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('game_index', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('issues_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'game_index', name='uq_lenses_doc_game')
    )
    with op.batch_alter_table('lens_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lens_reports_document_id'), ['document_id'], unique=False)

    op.create_table('mirror_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('game_index', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('last_text', sa.Text(), nullable=True),
    sa.Column('last_json', sa.Text(), nullable=True),
    sa.Column('author_answer', sa.Text(), nullable=True),
    sa.Column('map_json', sa.Text(), nullable=True),
    sa.Column('issues_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('ready_to_proceed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('gate2_status', sa.String(length=16), nullable=False),
    sa.Column('gate2_runs', sa.Integer(), nullable=False),
    sa.Column('gate2_text', sa.Text(), nullable=True),
    sa.Column('gate2_json', sa.Text(), nullable=True),
    sa.Column('gate2_answer', sa.Text(), nullable=True),
    sa.Column('gate2_error', sa.Text(), nullable=True),
    sa.Column('simulation_blocking', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'game_index', name='uq_mirror_doc_game')
    )
    with op.batch_alter_table('mirror_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mirror_sessions_document_id'), ['document_id'], unique=False)

    op.create_table('redesign_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('game_index', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=24), nullable=True),
    sa.Column('trigger_reason', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('issues_json', sa.Text(), nullable=True),
    sa.Column('spec_before_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'game_index', 'attempt_number', name='uq_redesign_doc_game_attempt')
    )
    with op.batch_alter_table('redesign_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redesign_attempts_document_id'), ['document_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_document_id'), ['document_id'], unique=False)

    op.create_table('synthesis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('game_index', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('reference_json', sa.Text(), nullable=True),
    sa.Column('issues_json', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('score_confidence', sa.String(length=16), nullable=True),
    sa.Column('revision_required', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'game_index', 'attempt_number', name='uq_synthesis_doc_game_attempt')
    )
    with op.batch_alter_table('synthesis_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_synthesis_reports_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('synthesis_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_synthesis_reports_document_id'))

    op.drop_table('synthesis_reports')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_document_id'))

    op.drop_table('reports')
    with op.batch_alter_table('redesign_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redesign_attempts_document_id'))

    op.drop_table('redesign_attempts')
    with op.batch_alter_table('mirror_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mirror_sessions_document_id'))

    op.drop_table('mirror_sessions')
    with op.batch_alter_table('lens_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lens_reports_document_id'))

    op.drop_table('lens_reports')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_step'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_document_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('game_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_specs_document_id'))

    op.drop_table('game_specs')
    with op.batch_alter_table('game_skeletons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_skeletons_document_id'))

    op.drop_table('game_skeletons')
    with op.batch_alter_table('diagnosis_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_reports_document_id'))

    op.drop_table('diagnosis_reports')
    with op.batch_alter_table('balance_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_reports_document_id'))

    op.drop_table('balance_reports')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_documents_file_hash'))

    op.drop_table('documents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tg_tag'))

    op.drop_table('users')
    # ### end Alembic commands ###
